---
- name: Wait for WinRM to respond after reboot
  wait_for:
    host: "{{ ansible_host | default(inventory_hostname) }}"
    port: 5985
    state: started
    delay: 20
    timeout: 600
  delegate_to: localhost
  register: winrm_reconnect_status
